### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by c-val** [tillrohrmann/cep-monitoring#1]
First, thank you for the code and its very interesting, related blog.

The import below in class CEPMonitoring does not resolve for me :
`import org.apache.flink.util.Collector;`

The import below in class MonitoringEventSource does not resolve either :
`import org.apache.flink.configuration.Configuration;`

I added flink-cep_2.11-1.0.1.jar and flink-streaming-java_2.11-1.0.1.jar, downloaded from The Central Repository, as libraries (I didn't use Maven on purpose, not working for me).

When I go to the [Flink source code](https://github.com/apache/flink), I don't find any flink-util nor flink-configuration.

The two "evt.getTemperature()" do not work for me either in the CEPMonitoring class.

Could you help me out here?

Thanks a lot,
Charles

**Comment by tillrohrmann** [comment]
Hi Charles,

if you don't use Maven for the dependency management but instead download the dependencies manually, then you have to make sure that you also provide all transitive dependencies. So for example, `flink-streaming-java` depends on `flink-core`. That is the reason why the imports cannot be resolved properly.

The following list shows the complete tree of dependencies which is required for the program. So if you want to build the program without Maven, then you have to download all these dependencies:

```
INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ cep-monitoring ---
[INFO] org.stsffap:cep-monitoring:jar:1.0
[INFO] +- org.apache.flink:flink-streaming-java_2.11:jar:1.0.1:compile
[INFO] |  +- org.apache.flink:flink-core:jar:1.0.1:compile
[INFO] |  |  +- org.apache.flink:flink-annotations:jar:1.0.1:compile
[INFO] |  |  +- com.esotericsoftware.kryo:kryo:jar:2.24.0:compile
[INFO] |  |  |  +- com.esotericsoftware.minlog:minlog:jar:1.2:compile
[INFO] |  |  |  \- org.objenesis:objenesis:jar:2.1:compile
[INFO] |  |  +- org.apache.avro:avro:jar:1.7.6:compile
[INFO] |  |  |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] |  |  |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |  |  |  \- com.thoughtworks.paranamer:paranamer:jar:2.3:compile
[INFO] |  |  \- org.apache.flink:flink-shaded-hadoop2:jar:1.0.1:compile
[INFO] |  |     +- xmlenc:xmlenc:jar:0.52:compile
[INFO] |  |     +- commons-codec:commons-codec:jar:1.4:compile
[INFO] |  |     +- commons-io:commons-io:jar:2.4:compile
[INFO] |  |     +- commons-net:commons-net:jar:3.1:compile
[INFO] |  |     +- commons-collections:commons-collections:jar:3.2.1:compile
[INFO] |  |     +- javax.servlet:servlet-api:jar:2.5:compile
[INFO] |  |     +- org.mortbay.jetty:jetty-util:jar:6.1.26:compile
[INFO] |  |     +- com.sun.jersey:jersey-core:jar:1.9:compile
[INFO] |  |     +- commons-el:commons-el:jar:1.0:runtime
[INFO] |  |     +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  |     +- com.jamesmurty.utils:java-xmlbuilder:jar:0.4:compile
[INFO] |  |     +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |     +- commons-configuration:commons-configuration:jar:1.7:compile
[INFO] |  |     +- commons-digester:commons-digester:jar:1.8.1:compile
[INFO] |  |     +- org.xerial.snappy:snappy-java:jar:1.0.5:compile
[INFO] |  |     +- com.jcraft:jsch:jar:0.1.42:compile
[INFO] |  |     +- org.apache.commons:commons-compress:jar:1.4.1:compile
[INFO] |  |     +- org.tukaani:xz:jar:1.0:compile
[INFO] |  |     +- commons-beanutils:commons-beanutils-bean-collections:jar:1.8.3:compile
[INFO] |  |     +- commons-daemon:commons-daemon:jar:1.0.13:compile
[INFO] |  |     +- javax.xml.bind:jaxb-api:jar:2.2.2:compile
[INFO] |  |     +- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO] |  |     +- javax.activation:activation:jar:1.1:compile
[INFO] |  |     +- com.google.inject:guice:jar:3.0:compile
[INFO] |  |     +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |     \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- org.apache.flink:flink-runtime_2.11:jar:1.0.1:compile
[INFO] |  |  +- org.apache.flink:flink-java:jar:1.0.1:compile
[INFO] |  |  +- commons-cli:commons-cli:jar:1.2:compile
[INFO] |  |  +- io.netty:netty-all:jar:4.0.27.Final:compile
[INFO] |  |  +- org.javassist:javassist:jar:3.18.2-GA:compile
[INFO] |  |  +- org.scala-lang:scala-library:jar:2.11.7:compile
[INFO] |  |  +- com.typesafe.akka:akka-actor_2.11:jar:2.3.7:compile
[INFO] |  |  |  \- com.typesafe:config:jar:1.2.1:compile
[INFO] |  |  +- com.typesafe.akka:akka-remote_2.11:jar:2.3.7:compile
[INFO] |  |  |  +- io.netty:netty:jar:3.8.0.Final:compile
[INFO] |  |  |  +- com.google.protobuf:protobuf-java:jar:2.5.0:compile
[INFO] |  |  |  \- org.uncommons.maths:uncommons-maths:jar:1.2.2a:compile
[INFO] |  |  +- com.typesafe.akka:akka-slf4j_2.11:jar:2.3.7:compile
[INFO] |  |  +- org.clapper:grizzled-slf4j_2.11:jar:1.0.2:compile
[INFO] |  |  +- com.github.scopt:scopt_2.11:jar:3.2.0:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-core:jar:3.1.0:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jvm:jar:3.1.0:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-json:jar:3.1.0:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.4.2:compile
[INFO] |  |  |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.4.0:compile
[INFO] |  |  |     \- com.fasterxml.jackson.core:jackson-core:jar:2.4.2:compile
[INFO] |  |  +- org.apache.zookeeper:zookeeper:jar:3.4.6:compile
[INFO] |  |  |  \- jline:jline:jar:0.9.94:compile
[INFO] |  |  |     \- junit:junit:jar:3.8.1:compile
[INFO] |  |  \- com.twitter:chill_2.11:jar:0.7.4:compile
[INFO] |  |     \- com.twitter:chill-java:jar:0.7.4:compile
[INFO] |  +- org.apache.flink:flink-clients_2.11:jar:1.0.1:compile
[INFO] |  |  \- org.apache.flink:flink-optimizer_2.11:jar:1.0.1:compile
[INFO] |  +- org.apache.commons:commons-math:jar:2.2:compile
[INFO] |  +- org.apache.sling:org.apache.sling.commons.json:jar:2.0.6:compile
[INFO] |  +- org.apache.commons:commons-math3:jar:3.5:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.3.2:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.7:compile
[INFO] |  +- org.slf4j:slf4j-log4j12:jar:1.7.7:compile
[INFO] |  +- log4j:log4j:jar:1.2.17:compile
[INFO] |  \- org.apache.flink:force-shading:jar:1.0.1:compile
[INFO] \- org.apache.flink:flink-cep_2.11:jar:1.0.1:compile
```

I hope this solves your problem.

Cheers,
Till

**Comment by c-val** [comment]
Thanks a lot Till,

It did solve my problem, I can now compile the code.
BUT, when I run it, I get the following :

```

Exception in thread "main" org.apache.flink.api.common.functions.InvalidTypesException: The generic type parameters of 'Map' are missing. 
It seems that your compiler has not stored them into the .class file. 
Currently, only the Eclipse JDT compiler preserves the type information necessary to use the lambdas feature type-safely. 
See the documentation for more information about how to compile jobs containing lambda expressions.
    at org.apache.flink.api.java.typeutils.TypeExtractor.validateLambdaGenericParameter(TypeExtractor.java:1316)
    at org.apache.flink.api.java.typeutils.TypeExtractor.validateLambdaGenericParameters(TypeExtractor.java:1302)
    at org.apache.flink.api.java.typeutils.TypeExtractor.getUnaryOperatorReturnType(TypeExtractor.java:346)
    at org.apache.flink.cep.PatternStream.select(PatternStream.java:64)
    at PACKAGE.CEPMonitoring.main(CEPMonitoring.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)coucou4

    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

Which refers to the line :
`DataStream<TemperatureWarning> warnings = tempPatternStream.select(`

_Please note that I use Intellij (I get the same with Eclipse though) and that I changed to the Eclipse Java compiler as instructed in your README.md._

Is there any way to change the code to get it running?

Thanks,
Charles

**Comment by tillrohrmann** [comment]
Have you rebuilt your project after changing to the Eclipse compiler in IntelliJ? For Eclipse there is also a [Java 8 guide](https://ci.apache.org/projects/flink/flink-docs-master/apis/java8.html) which might help you.

I've tested it again on my machine, in it works with IntelliJ and with Maven as described.

**Comment by c-val** [comment]
Thank you Till, it works like a charm!
