### ISSUE TITLE
can't run on IntelliJ - Compiler doesn't work

### ISSUE THREAD

**Issue by itsBen** [tillrohrmann/cep-monitoring#10]
Hey Guys,

I cloned the rep on my local machine, got JRE8 and latest IntelliJ. I set up IntelliJ to use Eclipse as Compiler  and version to 1.8. The language level is set to 8.

When I try to run CEPMonitoring.java following error is displayed:

`Exception in thread "main" org.apache.flink.api.common.functions.InvalidTypesException: The generic type parameters of 'Map' are missing. 
It seems that your compiler has not stored them into the .class file. 
Currently, only the Eclipse JDT compiler preserves the type information necessary to use the lambdas feature type-safely. 
See the documentation for more information about how to compile jobs containing lambda expressions.
	at org.apache.flink.api.java.typeutils.TypeExtractor.validateLambdaGenericParameter(TypeExtractor.java:1316)
	at org.apache.flink.api.java.typeutils.TypeExtractor.validateLambdaGenericParameters(TypeExtractor.java:1302)
	at org.apache.flink.api.java.typeutils.TypeExtractor.getUnaryOperatorReturnType(TypeExtractor.java:346)
	at org.apache.flink.cep.PatternStream.select(PatternStream.java:64)
	at org.stsffap.cep.monitoring.CEPMonitoring.main(CEPMonitoring.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)`

Did I miss something ? Can't figure out why it doesn't work, got any ideas?

Thanks,
Ben

**Comment by stephen-lazarionok** [comment]
I am having the same issue.

**Comment by tillrohrmann** [comment]
Flink jobs containing Java 8 lambdas cannot be compiled with IntelliJ IDEA at the moment. What you have to do is to build the project on the cli using `maven`. Once the program has been built via `maven`, you can also run it from within IntelliJ.

I hope this makes it work for you. I also corrected the `README.md`.
