### ISSUE TITLE
Insufficient number of network buffers

### ISSUE THREAD

**Issue by c-val** [tillrohrmann/cep-monitoring#7]
Hi everyone,

When I run this project with a local flink I get the following Exception while my conf taskmanager.network.numberOfBuffers is set to 4096. Any hint?

Exception in thread "main" org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
        at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$7.apply$mcV$sp(JobManager.scala:716)
        at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$7.apply(JobManager.scala:662)
        at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$7.apply(JobManager.scala:662)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.IOException: Insufficient number of network buffers: required 24, but only 8 available. The total number of network buffers is currently set to 2048. You can increase this number by setting the configuration key 'taskmanager.network.numberOfBuffers'.
        at org.apache.flink.runtime.io.network.buffer.NetworkBufferPool.createBufferPool(NetworkBufferPool.java:196)
        at org.apache.flink.runtime.io.network.NetworkEnvironment.registerTask(NetworkEnvironment.java:327)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:469)
        at java.lang.Thread.run(Thread.java:745)

**Comment by tillrohrmann** [comment]
Do you run the program from within the IDE or on a standalone/YARN cluster?

**Comment by tillrohrmann** [comment]
In the former case, you can either decrease the parallelism or create a `LocalStreamEnvironment` via `StreamExecutionEnvironment.createLocalEnvironment` where you can provide a configuration. The configuration should then contain the number of network buffers you want the system to run with. 

In the latter case, it seems  as if your configuration is not correctly read because the exception says that you've set the value to 2048. Please check that you modified the correct configuration file.

**Comment by c-val** [comment]
Hi Till*,

I am running the program on a standalone for now, but plan to run it on a YARN cluster. I did restart (./bin/start-local.sh and ./bin/stop-local.sh) several times after changing the conf file to set 'taskmanager.network.numberOfBuffers' to 4096 and then to 8192.
I'm going to try LocalStreamEnv., will let u know.

Thanks,
Charles

**Comment by c-val** [comment]
(in the server, /jobmanager/config ==> 'taskmanager.network.numberOfBuffers' rightly shows 8192)

**Comment by tillrohrmann** [comment]
Alright, so the cluster picks the configuration correctly up. What if you set the number of network buffers to 65536, for example?

**Comment by c-val** [comment]
My Parallelism was indeed 24, I set it to 8 and it worked. I then get the following exception :

```
Caused by: java.lang.NoSuchMethodError: java.lang.Double.hashCode(D)I
        at fr.edf.loop.cep.events.TemperatureEvent.hashCode(TemperatureEvent.java:51)
```

Would it be because of the Java version which is 7 in my case? (I can't have 8 on my YARN cluster).
I am going to give your conf for the nber of netwrk buf a try.

Thanks,

**Comment by c-val** [comment]
When I set the nbr of netwrk buf. to 65536, the server simply don't start.

**Comment by c-val** [comment]
I changed each call to
`Double.hashCode(***);`
To
`new Double(temperature).hashCode()`
